const mongoose = require("mongoose");
const db = require("../models/index.js");

mongoose.connect(process.env.MONODB_URI || "mongodb://localhost/aninder");

const lines = [
    "I'm here for a good time not a long time.",
    "Well, here I am. What are your other two wishes?",
    "Are you French? Because Eiffel for you.",
    "If I could rearrange the alphabet, I’d put ‘U’ and ‘I’ together.",
    "I'm no photographer, but I can picture us together.",
    "I was blinded by your beauty; I’m going to need your name and phone number for insurance purposes.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Are you a bank loan? Because you got my interest.",
    "Did the sun come out or did you just smile at me?",
    "My list of favourite things: Toys, Food, My Human, You?",
    "Can I borrow your cellphone? I need to call animal control cause I just saw a fox!",
    "Are you a mermaid, cause your cute as shell.",
    "Wanna go on a picnic? Alpaca lunch.",
    "Light travels faster than sound. That's why some people appear bright until you hear them speak",
    "I was wondering why the ball was getting bigger. Then it hit me",
    "I have a few jokes about unemployed people, but none of them work",
    "I Renamed my iPod The Titanic, so when I plug it in, it says “The Titanic is syncing.”",
    "When life gives you melons, you're dyslexic",
    "Last night, I dreamed I was swimming in an ocean of orange soda. But it was just a Fanta sea",
    "What’s the difference between a hippo and a zippo? One is really heavy and the other is a little lighter",
    "I can’t believe I got fired from the calendar factory. All I did was take a day off",
    "The man who survived pepper spray and mustard gas is now a seasoned veteran",
    "My dad farted in an elevator, it was wrong on so many levels",
    "Hear about the new restaurant called Karma? There’s no menu - you get what you deserve",
    "I went to buy some camouflage trousers yesterday but couldn't find any",
    "What do you call a bee that can’t make up its mind? A maybe",
    "I tried to sue the airline for losing my luggage. I lost my case",
    "England doesn't have a kidney bank, but it does have a Liverpool",
    "All chemists know that alcohol is always a solution",
    "Jill broke her finger today, but on the other hand she was completely fine",
    "The furniture store keeps calling me to come back. But all I wanted was one night stand",
    "When everything is coming your way, you're in the wrong lane",
    "Well, here I am. What are your other two wishes?",
    "If you were a chicken, you’d be impeccable.",
    "Are you a camera? Because every time I look at you, I smile.",
    "Fun Fact! A cow-bison hybrid is called a “beefalo”",
    "Did you know? In Switzerland it is illegal to own just one guinea pig.",
    "People say nothing is impossible, but I do nothing every day.",
    "If I were two-faced, would I be wearing this one?”",
    "The best thing about the future is that it comes one day at a time.",
    "he only mystery in life is why the kamikaze pilots wore helmets.",
    "Light travels faster than sound. This is why some people appear bright until you hear them speak.",
    "I don’t believe in astrology; I’m a Sagittarius and we’re skeptical.”",
    "Sometimes I wish I was an octopus, so I could slap eight people at once.",
];